stages:
  - style-check
  - build
  - test

variables:
  FEDORA_MB: registry.freedesktop.org/telepathy/telepathy-gabble/fedoraw:v2
  DEBIAN_MB: registry.freedesktop.org/telepathy/telepathy-gabble/debtest:v2
  DEBSTB_MB: registry.freedesktop.org/telepathy/telepathy-gabble/debstbl:v2
  SUSELP_MB: registry.freedesktop.org/telepathy/telepathy-gabble/osuselp:v2
  # OpenSUSE Tumbleweed has broken Twisted, can still be used in wocky CI
  SUSETW_MB: registry.freedesktop.org/telepathy/telepathy-gabble/osusetw:v1
  WOCKY_DEBUG: all
  #G_MESSAGES_DEBUG: all

.def_mb:
  before_script:
    - test -d _b || meson _b -Dgoogle-relay=true
  cache:
    key: "$CI_JOB_IMAGE:$CI_COMMIT_SHA"
    paths: [ _b ]

.def_ac:
  before_script:
    - sh autogen.sh
  cache:
    key: "AC:$CI_JOB_IMAGE:$CI_COMMIT_SHA"
    paths:
      - src/.libs
      - plugins/.libs
      - extensions/_gen
      - extensions/.libs
      - lib/gibber/.libs
      - lib/ext/wocky/wocky/.libs
      - tests/.libs
      - tests/twisted/.libs

style-ck-mb:
  extends: .def_mb
  stage: style-check
  image: $FEDORA_MB
  script:
    - ninja -C _b check

build-mb:
  extends: .def_mb
  stage: build
  image: $image
  script:
    - ninja -C _b
  parallel:
    matrix:
      - image:
        - $FEDORA_MB
        - $DEBIAN_MB
        #- $SUSETW_MB
        - $DEBSTB_MB
        - $SUSELP_MB

test-mb:
  extends: .def_mb
  stage: test
  image: $image
  script:
    - meson test -C _b
  artifacts:
    reports:
    expire_in: 1 week
    when: always
    paths:
      - "_b/meson-logs"
      - "_b/tests/twisted/tools/gabble-testing.log"
  parallel:
    matrix:
      - image:
        - $FEDORA_MB
        - $DEBIAN_MB
        #- $SUSETW_MB
        - $DEBSTB_MB
        - $SUSELP_MB

test-ac:
  extends: .def_ac
  stage: test
  image: $image
  script:
    - make
    - make check
  artifacts:
    reports:
    expire_in: 1 week
    when: always
    paths:
      - "FIXME.out"
      - "tests/twisted/tools/gabble-testing.log"
  parallel:
    matrix:
      - image:
        - $FEDORA_MB
        - $DEBIAN_MB
        #- $SUSETW_MB
        - $DEBSTB_MB
        - $SUSELP_MB

