name: Simple CI
on:
  push:
  pull_request:

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    container:
      image: registry.freedesktop.org/telepathy/telepathy-gabble/debstbl:v1
      options: -u 0:0
    timeout-minutes: 5
    steps:
      # git clone --depth 20 -b meson https://github.com/rufferson/telepathy-gabble.git && cd telepathy-gabble
    - uses: actions/checkout@v2
    - name: Repoint to local wocky
      run: sed -i '/freedesktop/s/^/#/;/github/s/^#//' subprojects/wocky.wrap
    - name: Configure
      run: meson _b -Dgoogle-relay=true
    - name: Syntax Check
      run: ninja -C_b check

  buildntest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - registry.freedesktop.org/telepathy/telepathy-gabble/debstbl:v1
          - registry.freedesktop.org/telepathy/telepathy-gabble/osuselp:v1
          - registry.freedesktop.org/telepathy/telepathy-gabble/fedoraw:v1
    container:
      image: ${{ matrix.image }}
      options: -u 0:0
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Repoint to local wocky
      run: sed -i '/freedesktop/s/^/#/;/github/s/^#//' subprojects/wocky.wrap
    - name: Configure
      run: meson _b -Dgoogle-relay=true
    - name: Build
      run: ninja -C_b
    - name: Test
      run: meson test -C_b
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: meson-logs
        path: |
          _b/meson-logs/*
          _b/tests/twisted/tools/gabble-testing.log
      if: ${{ always() }}

  autobuild:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Install prereqs
      run: |-
        sudo apt-get update && sudo apt-get install --no-install-recommends -qq -y build-essential \
        ccache automake libtool libglib2.0-dev glib-networking libtelepathy-glib-dev libsasl2-dev \
        libxml2-dev libsoup2.4-dev libsasl2-modules-gssapi-mit gnutls-bin libsqlite3-dev xsltproc \
        libssl-dev libgnutls28-dev libnice-dev python3-twisted python3-dbus
    - name: Bootstrap and Config
      run: bash autogen.sh
    - name: Build
      run: make
    - name: Test
      run: make check
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: automake-logs
        path: |
          tests/twisted/tools/gabble-testing.log
          FIXME.out
      if: ${{ always() }}
